//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.EMSPortal.UI.SharePoint.Layouts.EMSPortal {
    
    
    public partial class get {
        
        /// <summary>
        /// production control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor production;
        
        /// <summary>
        /// qa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor qa;
    }
}
/*+- OmniWorks Replacement History - EPort`src`UI`SharePoint`Layouts`EMSPortal:get.aspx.designer.cs;1 */
/*       1*[1733916] 27-FEB-2013 20:54:29 (GMT) JMohan2 */
/*         "add get.aspx application page to the solution" */
/*+- OmniWorks Replacement History - EPort`src`UI`SharePoint`Layouts`EMSPortal:get.aspx.designer.cs;1 */
