//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.EMSPortal.UITester {
    
    
    public partial class Default {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ProjectList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect ProjectList;
    }
}
/*+- OmniWorks Replacement History - EPort`src`UITester:Default.aspx.designer.cs;1 */
/*       1*[1710695] 24-JUL-2013 20:05:31 (GMT) AMathew */
/*         "Adding UI Tester Project" */
/*+- OmniWorks Replacement History - EPort`src`UITester:Default.aspx.designer.cs;1 */
