//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLB.EMSPortal.UITester
{


    public partial class EmspeedContent
    {
    }
}
/*+- OmniWorks Replacement History - EPort`src`UITester:EmspeedContent.ascx.designer.cs;1 */
/*       1*[1793026] 25-SEP-2013 20:03:23 (GMT) AMathew */
/*         "styled loading and error pages" */
/*+- OmniWorks Replacement History - EPort`src`UITester:EmspeedContent.ascx.designer.cs;1 */
