
function getResults() {
    return [
   {
       "achievedValue": "",
       "dbId": "1000088341",
       "description": "",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 0,
       "maturityIndex": 0,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Design Specific",
       "numberOfTestsCompleted": 0,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 0,
       "prioritization": "03. Performance",
       "references": "",
       "reqId": "1",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088341&ignoreViewGroup=true",
       "sequence": 1,
       "target": "n/a",
       "testPassed": false,
       "tolerance": "n/a",
       "type": "Other",
       "typeSequence": "11",
       "typeShortDescription": "Other",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088341",
       "description": "",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 0,
       "maturityIndex": 0,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Design Specific",
       "numberOfTestsCompleted": 0,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 0,
       "prioritization": "03. Performance",
       "references": "",
       "reqId": "1",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088341&ignoreViewGroup=true",
       "sequence": 1,
       "target": "n/a",
       "testPassed": false,
       "tolerance": "n/a",
       "type": "Other",
       "typeSequence": "11",
       "typeShortDescription": "Other",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "3 min",
       "dbId": "1000088365",
       "description": "Time to send to surface at 6 bps with less than 5 psi errors on major pressure points for 1 hour curve",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.26,
       "maxRisk": 4,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "Pumps-off APWD profile through mud pulse telemetry",
       "numberOfTestsCompleted": 6,
       "numberOfTestsPassed": 2,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 5,
       "numberOfVerificationTestsPassed": 2,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 6,
       "prioritization": "01. Key Differentiators",
       "references": "",
       "reqId": "3",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088365&ignoreViewGroup=true",
       "sequence": 2,
       "target": "5 min",
       "testPassed": false,
       "tolerance": "2 to 7 min",
       "type": "Functional",
       "typeSequence": "1",
       "typeShortDescription": "Functional",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088415",
       "description": "Data quality of compressed NDG measurements",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.26,
       "maxRisk": 8,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "EcoScope's NGD measurements thorugh mud pulse telemetry",
       "numberOfTestsCompleted": 4,
       "numberOfTestsPassed": 2,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 3,
       "numberOfVerificationTestsPassed": 2,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 4,
       "prioritization": "01. Key Differentiators",
       "references": "",
       "reqId": "4",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088415&ignoreViewGroup=true",
       "sequence": 3,
       "target": "matching RM",
       "testPassed": false,
       "tolerance": "80% match",
       "type": "Functional",
       "typeSequence": "1",
       "typeShortDescription": "Functional",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088458",
       "description": "Average with current siren modulators",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.26,
       "maxRisk": 15,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "Physical data rates from 30k to 50k ft",
       "numberOfTestsCompleted": 8,
       "numberOfTestsPassed": 1,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 7,
       "numberOfVerificationTestsPassed": 1,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 8,
       "prioritization": "01. Key Differentiators",
       "references": "",
       "reqId": "5",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088458&ignoreViewGroup=true",
       "sequence": 4,
       "target": "4 bps",
       "testPassed": false,
       "tolerance": "2 to 6 bps",
       "type": "Functional",
       "typeSequence": "1",
       "typeShortDescription": "Functional",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088516",
       "description": "Coverage of different LWD measurements on 6-in BHA",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.26,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Data compression coverage",
       "numberOfTestsCompleted": 1,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 1,
       "prioritization": "01. Key Differentiators",
       "references": "",
       "reqId": "6",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088516&ignoreViewGroup=true",
       "sequence": 5,
       "target": "0.9",
       "testPassed": false,
       "tolerance": "50 to 100%",
       "type": "System Combinability / Compatibility with higher level, other systems",
       "typeSequence": "9",
       "typeShortDescription": "System Comp.",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "6",
       "dbId": "1000088546",
       "description": "Rig and well model to help setup surface sensors",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.26,
       "maxRisk": 2,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "SPT placement application for different conditions",
       "numberOfTestsCompleted": 2,
       "numberOfTestsPassed": 1,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 1,
       "numberOfVerificationTestsPassed": 1,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 2,
       "prioritization": "01. Key Differentiators",
       "references": "",
       "reqId": "7",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088546&ignoreViewGroup=true",
       "sequence": 6,
       "target": "Support 6 sensors",
       "testPassed": false,
       "tolerance": "4 to 8",
       "type": "Functional",
       "typeSequence": "1",
       "typeShortDescription": "Functional",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088577",
       "description": "Improvement depends on particular tool",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 2,
       "maturityIndex": 0.13,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "RT LWD improvements through data compression",
       "numberOfTestsCompleted": 3,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 2,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 3,
       "prioritization": "01. Key Differentiators",
       "references": "",
       "reqId": "8",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088577&ignoreViewGroup=true",
       "sequence": 7,
       "target": "",
       "testPassed": false,
       "tolerance": "",
       "type": "Functional",
       "typeSequence": "1",
       "typeShortDescription": "Functional",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088611",
       "description": "Number of trining sessions per year",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.26,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Training to Instructors and Intouch/OSC engineers",
       "numberOfTestsCompleted": 1,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 1,
       "prioritization": "01. Key Differentiators",
       "references": "",
       "reqId": "9",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088611&ignoreViewGroup=true",
       "sequence": 8,
       "target": "1",
       "testPassed": false,
       "tolerance": "1 to 2",
       "type": "Other",
       "typeSequence": "11",
       "typeShortDescription": "Other",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088638",
       "description": "Improve data sample rate (ex. BHA with ROP of 100 ft/h)",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.2,
       "maxRisk": 9,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "Compression on DDR/EMLA",
       "numberOfTestsCompleted": 4,
       "numberOfTestsPassed": 1,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 3,
       "numberOfVerificationTestsPassed": 1,
       "parenttypeSequence": "1",
       "percentOfTestsCompleted": 4,
       "prioritization": "02. Must Have",
       "references": "",
       "reqId": "10",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088638&ignoreViewGroup=true",
       "sequence": 9,
       "target": "3 ft sampling",
       "testPassed": false,
       "tolerance": "1 to 6 ft",
       "type": "Functional/RT LWD improvements through data compression",
       "typeSequence": "1.1",
       "typeShortDescription": "",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088679",
       "description": "Compression related failures during FT",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.2,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Compression reliability under designed conditions",
       "numberOfTestsCompleted": 1,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 1,
       "prioritization": "02. Must Have",
       "references": "",
       "reqId": "11",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088679&ignoreViewGroup=true",
       "sequence": 10,
       "target": "1% failures on FT runs",
       "testPassed": false,
       "tolerance": "0 to 2",
       "type": "Reliability",
       "typeSequence": "2",
       "typeShortDescription": "Reliability",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088706",
       "description": "Bit errors on average per 1000 bits",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.2,
       "maxRisk": 9,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "Demodulation error rates",
       "numberOfTestsCompleted": 2,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 1,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 2,
       "prioritization": "02. Must Have",
       "references": "",
       "reqId": "12",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088706&ignoreViewGroup=true",
       "sequence": 11,
       "target": "1 over 1000",
       "testPassed": false,
       "tolerance": "0 to 4",
       "type": "Reliability",
       "typeSequence": "2",
       "typeShortDescription": "Reliability",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088738",
       "description": "RSS dpoints in repeating frame of triple combo",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 2,
       "maturityIndex": 0.1,
       "maxRisk": 9,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "Bandwidth optimization for RSS tools",
       "numberOfTestsCompleted": 5,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 4,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "1",
       "percentOfTestsCompleted": 5,
       "prioritization": "02. Must Have",
       "references": "",
       "reqId": "13",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088738&ignoreViewGroup=true",
       "sequence": 12,
       "target": "20% of BW",
       "testPassed": false,
       "tolerance": "15 to 25%",
       "type": "Functional/RT LWD improvements through data compression",
       "typeSequence": "1.1",
       "typeShortDescription": "",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088783",
       "description": "Provide automatic advise on telemetry situation",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 3,
       "maturityIndex": 0.15,
       "maxRisk": 9,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "RT diagnostics and smart alarms",
       "numberOfTestsCompleted": 2,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 1,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 2,
       "prioritization": "02. Must Have",
       "references": "",
       "reqId": "14",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088783&ignoreViewGroup=true",
       "sequence": 13,
       "target": "Support 2 use cases",
       "testPassed": false,
       "tolerance": "2 to 4",
       "type": "Functional",
       "typeSequence": "1",
       "typeShortDescription": "Functional",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "0.59",
       "dbId": "1000088814",
       "description": "Model accuracy",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.2,
       "maxRisk": 2,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "SPT placement prediction accuracy",
       "numberOfTestsCompleted": 2,
       "numberOfTestsPassed": 1,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 1,
       "numberOfVerificationTestsPassed": 1,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 2,
       "prioritization": "02. Must Have",
       "references": "",
       "reqId": "15",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088814&ignoreViewGroup=true",
       "sequence": 14,
       "target": "50% accuracy",
       "testPassed": false,
       "tolerance": "40 to 100%",
       "type": "Reliability",
       "typeSequence": "2",
       "typeShortDescription": "Reliability",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088845",
       "description": "Not moving time wasted for telemetry reasons only",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.13,
       "maxRisk": 9,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "Bandwidth optimization for Pressure and Sampling tools",
       "numberOfTestsCompleted": 5,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 5,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "1",
       "percentOfTestsCompleted": 5,
       "prioritization": "03. Performance",
       "references": "",
       "reqId": "16",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088845&ignoreViewGroup=true",
       "sequence": 15,
       "target": "< 1 min",
       "testPassed": false,
       "tolerance": "0 to 5 min",
       "type": "Functional/RT LWD improvements through data compression",
       "typeSequence": "1.1",
       "typeShortDescription": "",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088892",
       "description": "Enable RT drilling optimization",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 2,
       "maturityIndex": 0.07,
       "maxRisk": 9,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "Drilling Mechanics/Dynamics data through mud pulse telemetry",
       "numberOfTestsCompleted": 3,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 2,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "1",
       "percentOfTestsCompleted": 3,
       "prioritization": "03. Performance",
       "references": "",
       "reqId": "17",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088892&ignoreViewGroup=true",
       "sequence": 16,
       "target": "Data on demand",
       "testPassed": false,
       "tolerance": "",
       "type": "Functional/RT LWD improvements through data compression",
       "typeSequence": "1.1",
       "typeShortDescription": "",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088935",
       "description": "Provide cD&I, TF, and multi-curve on azi.GR compression",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.13,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "DVDxT150 compression",
       "numberOfTestsCompleted": 3,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 2,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "1",
       "percentOfTestsCompleted": 3,
       "prioritization": "03. Performance",
       "references": "",
       "reqId": "18",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088935&ignoreViewGroup=true",
       "sequence": 17,
       "target": "matching ImPulse",
       "testPassed": false,
       "tolerance": "0",
       "type": "Functional/RT LWD improvements through data compression",
       "typeSequence": "1.1",
       "typeShortDescription": "",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088969",
       "description": "Ease of usage  and optimization during operation",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.13,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Ease of Operation of new Applications",
       "numberOfTestsCompleted": 1,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 1,
       "prioritization": "03. Performance",
       "references": "",
       "reqId": "19",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088969&ignoreViewGroup=true",
       "sequence": 18,
       "target": "",
       "testPassed": false,
       "tolerance": "",
       "type": "Usability",
       "typeSequence": "5",
       "typeShortDescription": "Usability",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000088996",
       "description": "Max CPU usage of algorithms in field machines",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.13,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "HSPM dependency",
       "numberOfTestsCompleted": 2,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 1,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 2,
       "prioritization": "03. Performance",
       "references": "",
       "reqId": "20",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000088996&ignoreViewGroup=true",
       "sequence": 19,
       "target": "0.25",
       "testPassed": false,
       "tolerance": "0 to 30%",
       "type": "System Combinability / Compatibility with higher level, other systems",
       "typeSequence": "9",
       "typeShortDescription": "System Comp.",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000089026",
       "description": "Compression algorithms designed taking into account downhole tool constraints",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.13,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Downhole tool algorithms",
       "numberOfTestsCompleted": 0,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 0,
       "prioritization": "03. Performance",
       "references": "",
       "reqId": "21",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000089026&ignoreViewGroup=true",
       "sequence": 20,
       "target": "",
       "testPassed": false,
       "tolerance": "",
       "type": "System Combinability / Compatibility with higher level, other systems",
       "typeSequence": "9",
       "typeShortDescription": "System Comp.",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000089051",
       "description": "Compression algorithms of the same type of measurement can be re-used by different tools",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0.13,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Re-use of algorithms",
       "numberOfTestsCompleted": 0,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 0,
       "prioritization": "03. Performance",
       "references": "",
       "reqId": "22",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000089051&ignoreViewGroup=true",
       "sequence": 21,
       "target": "",
       "testPassed": false,
       "tolerance": "",
       "type": "System Combinability / Compatibility with higher level, other systems",
       "typeSequence": "9",
       "typeShortDescription": "System Comp.",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000089076",
       "description": "Time to send 620 ms waveform to surface at 6 bps with agreed accuracy",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 1,
       "maturityIndex": 0,
       "maxRisk": 9,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "Compression on Seismic measurements",
       "numberOfTestsCompleted": 5,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 4,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "1",
       "percentOfTestsCompleted": 5,
       "prioritization": "05. Indifferent",
       "references": "",
       "reqId": "23",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000089076&ignoreViewGroup=true",
       "sequence": 22,
       "target": "2 min",
       "testPassed": false,
       "tolerance": "1 to 5 min",
       "type": "Functional/RT LWD improvements through data compression",
       "typeSequence": "1.1",
       "typeShortDescription": "",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000089124",
       "description": "Software and firmware distribution through normal channels",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Software and firmware distribution",
       "numberOfTestsCompleted": 0,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 0,
       "prioritization": "05. Indifferent",
       "references": "",
       "reqId": "24",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000089124&ignoreViewGroup=true",
       "sequence": 23,
       "target": "",
       "testPassed": false,
       "tolerance": "",
       "type": "Manufacturability",
       "typeSequence": "3",
       "typeShortDescription": "Manufacturability",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000089149",
       "description": "Mean time required to respond to InTouch queries",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Mean Time to Respond to InTouch queries",
       "numberOfTestsCompleted": 0,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 0,
       "prioritization": "05. Indifferent",
       "references": "",
       "reqId": "25",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000089149&ignoreViewGroup=true",
       "sequence": 24,
       "target": "<1 day",
       "testPassed": false,
       "tolerance": "0.5 to 3 days",
       "type": "Maintainability",
       "typeSequence": "4",
       "typeShortDescription": "Maintainability",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000089174",
       "description": "As a % of BHA costs",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Operational cost per job of Orion improvements",
       "numberOfTestsCompleted": 0,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 0,
       "prioritization": "05. Indifferent",
       "references": "",
       "reqId": "26",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000089174&ignoreViewGroup=true",
       "sequence": 25,
       "target": "< 1%",
       "testPassed": false,
       "tolerance": "0 to 2%",
       "type": "Total Cost of Ownership",
       "typeSequence": "6",
       "typeShortDescription": "Total C.O.",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000089199",
       "description": "Time to Commercialization",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0,
       "maxRisk": 6,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "Project Development Time",
       "numberOfTestsCompleted": 0,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 0,
       "prioritization": "05. Indifferent",
       "references": "",
       "reqId": "27",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000089199&ignoreViewGroup=true",
       "sequence": 26,
       "target": "3 years",
       "testPassed": false,
       "tolerance": "2 to 3.5 years",
       "type": "Development Time",
       "typeSequence": "7",
       "typeShortDescription": "Development Time",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000089226",
       "description": "Project total NPD cost",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "NPD costs",
       "numberOfTestsCompleted": 0,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 0,
       "prioritization": "05. Indifferent",
       "references": "",
       "reqId": "28",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000089226&ignoreViewGroup=true",
       "sequence": 27,
       "target": "6750K USD",
       "testPassed": false,
       "tolerance": "4300K to 8500K",
       "type": "Development Cost",
       "typeSequence": "8",
       "typeShortDescription": "Development Cost",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000089251",
       "description": "% of new applications having online help",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0,
       "maxRisk": 0,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "",
       "name": "Online help for new applications",
       "numberOfTestsCompleted": 1,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 1,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 1,
       "prioritization": "05. Indifferent",
       "references": "",
       "reqId": "29",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000089251&ignoreViewGroup=true",
       "sequence": 28,
       "target": "1",
       "testPassed": false,
       "tolerance": "80 to 100%",
       "type": "Other",
       "typeSequence": "11",
       "typeShortDescription": "Other",
       "validationComment": "",
       "version": "1"
   },
   {
       "achievedValue": "",
       "dbId": "1000089279",
       "description": "No HSE issues as highlighted in hazerd inventory",
       "dirty": false,
       "isLocked": false,
       "isValidated": false,
       "maturity": 4,
       "maturityIndex": 0,
       "maxRisk": 6,
       "maxRiskCost": 0,
       "maxRiskPerformance": 0,
       "maxRiskTime": 0,
       "maxRiskType": "Undefined Category",
       "name": "Health, Safety and Environment",
       "numberOfTestsCompleted": 0,
       "numberOfTestsPassed": 0,
       "numberOfValidationTestsCompleted": 0,
       "numberOfValidationTestsPassed": 0,
       "numberOfVerificationTestsCompleted": 0,
       "numberOfVerificationTestsPassed": 0,
       "parenttypeSequence": "",
       "percentOfTestsCompleted": 0,
       "prioritization": "05. Indifferent",
       "references": "",
       "reqId": "30",
       "requirementUrl": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=Requirement&defaultRowId=1000089279&ignoreViewGroup=true",
       "sequence": 29,
       "target": "",
       "testPassed": false,
       "tolerance": "",
       "type": "HSE",
       "typeSequence": "10",
       "typeShortDescription": "HSE",
       "validationComment": "",
       "version": "1"
   }
]
}
function getFields() {
    return [
        { name: 'achievedValue', type: 'string' },
        { name: 'dbId', type: 'long' },
        { name: 'description', type: 'string' },
        { name: 'dirty', type: 'boolean' },
        { name: 'isLocked', type: 'boolean' },
        { name: 'isValidated', type: 'boolean' },
        { name: 'maturity', type: 'int' },
        { name: 'maturityIndex', type: 'float' },
        { name: 'maxRisk', type: 'float' },
        { name: 'maxRiskCost', type: 'float' },
        { name: 'maxRiskPerformance', type: 'float' },
        { name: 'maxRiskTime', type: 'float' },
        { name: 'maxRiskType', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'numberOfTestsCompleted', type: 'int' },
        { name: 'numberOfTestsPassed', type: 'int' },
        { name: 'numberOfValidationTestsCompleted', type: 'int' },
        { name: 'numberOfValidationTestsPassed', type: 'int' },
        { name: 'numberOfVerificationTestsCompleted', type: 'int' },
        { name: 'numberOfVerificationTestsPassed', type: 'int' },
        { name: 'parenttypeSequence', type: 'string' },
        { name: 'percentOfTestsCompleted', type: 'int' },
        { name: 'prioritization', type: 'string' },
        { name: 'references', type: 'array' },
        { name: 'reqId', type: 'long' },
        { name: 'requirementUrl', type: 'string' },
        { name: 'sequence', type: 'int' },
        { name: 'target', type: 'string' },
        { name: 'testPassed', type: 'boolean' },
        { name: 'tolerance', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'typeSequence', type: 'string' },
        { name: 'typeShortDescription', type: 'string' },
        { name: 'validationComment', type: 'string' },
        { name: 'version', type: 'string' }
    ]
}
function getParameters() {
    var o = {};
    o.theType = 'stature';
    o.theFields = getFields();

    o.theParams = { projectId: 97368 };
    o.theMethod = 'getRequirements';
    o.theRecord = 'requirements';

    return o;
}

StartTest(function (t) {
    var o = getParameters()
    var store = getTheStore(o);
    store.load({
        params: o.theParams,
        callback: function () {
            t.isDeeply(getJsonOfStore(store), getResults(), t.url)
        }
    });
})

//o.theElement = 'requirements';
//o.theAttribute = '[@xsi:type="ns1:Requirement"]';
//o.extraRootItem = 'urlToRequirementsWorksheet';
//o.theFields = getFields();


//function getFields() {
//    return [
//        { name: 'achievedValue', type: 'string' }, 
//        { name: 'dbId', type: 'long' },
//        { name: 'description', type: 'string' },
//        { name: 'dirty', type: 'boolean' },
//        { name: 'isLocked', type: 'boolean' },
//        { name: 'isValidated', type: 'boolean' },
//        { name: 'maturity', type: 'int' }, 
//        { name: 'maturityIndex', type: 'float' },
//        { name: 'maxRisk', type: 'float' },
//        { name: 'maxRiskCost', type: 'float' },
//        { name: 'maxRiskPerformance', type: 'float' }, 
//        { name: 'maxRiskTime', type: 'float' },
//        { name: 'maxRiskType', type: 'string' },
//        { name: 'name', type: 'string' },
//        { name: 'numberOfTestsCompleted', type: 'int' },
//        { name: 'numberOfTestsPassed', type: 'int' },
//        { name: 'numberOfValidationTestsCompleted', type: 'int' },
//        { name: 'numberOfValidationTestsPassed', type: 'int' },
//        { name: 'numberOfVerificationTestsCompleted', type: 'int' },
//        { name: 'numberOfVerificationTestsPassed', type: 'int' }, 
//        { name: 'parenttypeSequence', type: 'string' },
//        { name: 'percentOfTestsCompleted', type: 'int' },
//        { name: 'prioritization', type: 'string' }, 
//        { name: 'references', type: 'array' },
//        { name: 'reqId', type: 'long' },
//        { name: 'requirementUrl', type: 'string' },
//        { name: 'sequence', type: 'int' },
//        { name: 'target', type: 'string' },
//        { name: 'testPassed', type: 'boolean' },
//        { name: 'tolerance', type: 'string' },
//        { name: 'type', type: 'string' },
//        { name: 'typeSequence', type: 'string' },
//        { name: 'typeShortDescription', type: 'string' },
//        { name: 'validationComment', type: 'string' },
//        { name: 'version', type: 'string' }
//    ]
//}
