function getResults() {
    return [
   {
       "dbId": "1000089304",
       "description": "Algorithms takes too long to compute compressed curve",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Pumps-off APWD profile through mud pulse telemetry, Data compression, Spec 1",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "1",
       "riskScore": 4,
       "rpn": "",
       "sequence": 1,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089304&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089304",
       "description": "Algorithms takes too long to compute compressed curve",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Pumps-off APWD profile through mud pulse telemetry, Data compression, Spec 1",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "1",
       "riskScore": 4,
       "rpn": "",
       "sequence": 1,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089304&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089305",
       "description": "Decompressed channel data quality compromised due to compression",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Pumps-off APWD profile through mud pulse telemetry, Decompression, Spec 2",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "2",
       "riskScore": 4,
       "rpn": "",
       "sequence": 2,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089305&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089306",
       "description": "Data loss due to frames miss interpreted at surface",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Pumps-off APWD profile through mud pulse telemetry, Frame structure/downlink protocol, Spec 3",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "3",
       "riskScore": 2,
       "rpn": "",
       "sequence": 3,
       "severity": 1,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089306&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089307",
       "description": "DPOINTS received in error are fed back to the decompression algorithm",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Pumps-off APWD profile through mud pulse telemetry, Receivers and noise cancellation, Spec 4",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "4",
       "riskScore": 2,
       "rpn": "",
       "sequence": 4,
       "severity": 1,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089307&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089308",
       "description": "Data compression algorithm not behaving as during the feasibility tests (offline data)",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "EcoScope's NGD measurements thorugh mud pulse telemetry, Data compression, Spec 6",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "5",
       "riskScore": 4,
       "rpn": "",
       "sequence": 5,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089308&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089309",
       "description": "DPOINTS received in error are fed back to the decompression algorithm",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "EcoScope's NGD measurements thorugh mud pulse telemetry, Receivers and noise cancellation, Spec 7",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "6",
       "riskScore": 2,
       "rpn": "",
       "sequence": 6,
       "severity": 1,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089309&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089310",
       "description": "NGD measurements not recovered at surface, NGD channels quality compromised due to compression",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "EcoScope's NGD measurements thorugh mud pulse telemetry, Decompression, Spec 8",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "7",
       "riskScore": 6,
       "rpn": "",
       "sequence": 7,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089310&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089311",
       "description": "Modulation not recognized at surface due to channel distortion",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Physical data rates from 30k to 50k ft, Modulation, Spec 9",
       "residualOccurence": 0,
       "residualRiskScore": 9,
       "residualSeverity": 3,
       "riskRegistryId": "8",
       "riskScore": 15,
       "rpn": "",
       "sequence": 8,
       "severity": 5,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089311&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089313",
       "description": "Too many false alarms",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Physical data rates from 30k to 50k ft, Diagnostics, alarms, and automation, Spec 10",
       "residualOccurence": 0,
       "residualRiskScore": 4,
       "residualSeverity": 2,
       "riskRegistryId": "9",
       "riskScore": 9,
       "rpn": "",
       "sequence": 9,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089313&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089315",
       "description": "Receivers and noise cancellation not working below 7 dB SNR",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Physical data rates from 30k to 50k ft, Receivers and noise cancellation, Spec 12",
       "residualOccurence": 0,
       "residualRiskScore": 6,
       "residualSeverity": 3,
       "riskRegistryId": "10",
       "riskScore": 9,
       "rpn": "",
       "sequence": 10,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089315&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089317",
       "description": "Model not accurate",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Physical data rates from 30k to 50k ft, Pre-job preparation, Spec 13",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "11",
       "riskScore": 2,
       "rpn": "",
       "sequence": 11,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089317&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089318",
       "description": "Model not accurate",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "SPT placement application for different conditions, Pre-job preparation, Spec 16",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "12",
       "riskScore": 2,
       "rpn": "",
       "sequence": 12,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089318&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089319",
       "description": "Implementation errors",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Bandwidth optimization for Pressure and Sampling tools, Data compression, Spec 21",
       "residualOccurence": 0,
       "residualRiskScore": 2,
       "residualSeverity": 2,
       "riskRegistryId": "13",
       "riskScore": 9,
       "rpn": "",
       "sequence": 13,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089319&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089320",
       "description": "Data loss due to frames miss interpreted at surface",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Bandwidth optimization for Pressure and Sampling tools, Frame structure/downlink protocol, Spec 22",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "14",
       "riskScore": 2,
       "rpn": "",
       "sequence": 14,
       "severity": 1,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089320&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089321",
       "description": "Decompressed channel data quality compromised due to compression",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Bandwidth optimization for Pressure and Sampling tools, Decompression, Spec 23",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "15",
       "riskScore": 4,
       "rpn": "",
       "sequence": 15,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089321&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089322",
       "description": "Missing commands",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Bandwidth optimization for Pressure and Sampling tools, Frame structure/downlink protocol, Spec 24",
       "residualOccurence": 0,
       "residualRiskScore": 4,
       "residualSeverity": 2,
       "riskRegistryId": "16",
       "riskScore": 6,
       "rpn": "",
       "sequence": 16,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089322&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089323",
       "description": "Implementation errors",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Compression on DDR/EMLA, Data compression, Spec 26",
       "residualOccurence": 0,
       "residualRiskScore": 2,
       "residualSeverity": 2,
       "riskRegistryId": "17",
       "riskScore": 9,
       "rpn": "",
       "sequence": 17,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089323&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089324",
       "description": "DPOINTS received in error are fed back to the decompression algorithm",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Compression on DDR/EMLA, Receivers and noise cancellation, Spec 27",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "18",
       "riskScore": 2,
       "rpn": "",
       "sequence": 18,
       "severity": 1,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089324&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089325",
       "description": "Decompressed channel data quality compromised due to compression",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Compression on DDR/EMLA, Decompression, Spec 28",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "19",
       "riskScore": 4,
       "rpn": "",
       "sequence": 19,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089325&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089326",
       "description": "Implementation errors",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Bandwidth optimization for RSS tools, Data compression, Spec 29",
       "residualOccurence": 0,
       "residualRiskScore": 2,
       "residualSeverity": 2,
       "riskRegistryId": "20",
       "riskScore": 9,
       "rpn": "",
       "sequence": 20,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089326&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089327",
       "description": "Decompressed channel data quality compromised due to compression",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Bandwidth optimization for RSS tools, Decompression, Spec 30",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "21",
       "riskScore": 4,
       "rpn": "",
       "sequence": 21,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089327&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089328",
       "description": "Data loss due to frames miss interpreted at surface",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Bandwidth optimization for RSS tools, Frame structure/downlink protocol, Spec 31",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "22",
       "riskScore": 2,
       "rpn": "",
       "sequence": 22,
       "severity": 1,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089328&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089329",
       "description": "Algorithms takes too long to compute compressed curve",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Drilling Mechanics/Dynamics data through mud pulse telemetry, Data compression, Spec 33",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "23",
       "riskScore": 4,
       "rpn": "",
       "sequence": 23,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089329&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089330",
       "description": "Decompressed channel data quality compromised due to compression",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Drilling Mechanics/Dynamics data through mud pulse telemetry, Decompression, Spec 34",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "24",
       "riskScore": 4,
       "rpn": "",
       "sequence": 24,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089330&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089331",
       "description": "Data loss due to frames miss interpreted at surface",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Drilling Mechanics/Dynamics data through mud pulse telemetry, Frame structure/downlink protocol, Spec 35",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "25",
       "riskScore": 2,
       "rpn": "",
       "sequence": 25,
       "severity": 1,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089331&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089332",
       "description": "Implementation errors",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Compression on Seismic measurements, Data compression, Spec 41",
       "residualOccurence": 0,
       "residualRiskScore": 2,
       "residualSeverity": 2,
       "riskRegistryId": "26",
       "riskScore": 9,
       "rpn": "",
       "sequence": 26,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089332&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089333",
       "description": "DPOINTS received in error are fed back to the decompression algorithm",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Compression on Seismic measurements, Receivers and noise cancellation, Spec 42",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "27",
       "riskScore": 2,
       "rpn": "",
       "sequence": 27,
       "severity": 1,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089333&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089334",
       "description": "Decompressed channel data quality compromised due to compression",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Compression on Seismic measurements, Decompression, Spec 44",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "28",
       "riskScore": 4,
       "rpn": "",
       "sequence": 28,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089334&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089335",
       "description": "Data loss due to frames miss interpreted at surface",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Compression on Seismic measurements, Frame structure/downlink protocol, Spec 45",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "29",
       "riskScore": 2,
       "rpn": "",
       "sequence": 29,
       "severity": 1,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089335&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089336",
       "description": "Too many false alarms",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "RT diagnostics and smart alarms, Diagnostics, alarms, and automation, Spec 47",
       "residualOccurence": 0,
       "residualRiskScore": 4,
       "residualSeverity": 2,
       "riskRegistryId": "30",
       "riskScore": 9,
       "rpn": "",
       "sequence": 30,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089336&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089338",
       "description": "Receivers and noise cancellation not working below 7 dB SNR",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Demodulation error rates, Receivers and noise cancellation, Spec 49",
       "residualOccurence": 0,
       "residualRiskScore": 4,
       "residualSeverity": 2,
       "riskRegistryId": "31",
       "riskScore": 9,
       "rpn": "",
       "sequence": 31,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089338&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089340",
       "description": "Model not accurate",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "SPT placement prediction accuracy, Pre-job preparation, Spec 50",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "32",
       "riskScore": 2,
       "rpn": "",
       "sequence": 32,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089340&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089341",
       "description": "Budget reductions",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Project Development Time, Overall Product, Spec 55",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "33",
       "riskScore": 3,
       "rpn": "",
       "sequence": 33,
       "severity": 1,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089341&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089342",
       "description": "Missing data",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "EcoScope's NGD measurements thorugh mud pulse telemetry, Receivers and noise cancellation",
       "residualOccurence": 0,
       "residualRiskScore": 4,
       "residualSeverity": 2,
       "riskRegistryId": "34",
       "riskScore": 8,
       "rpn": "",
       "sequence": 34,
       "severity": 4,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089342&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089345",
       "description": "Decoding false commands",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Bandwidth optimization for Pressure and Sampling tools, Frame structure/downlink protocol",
       "residualOccurence": 0,
       "residualRiskScore": 4,
       "residualSeverity": 2,
       "riskRegistryId": "35",
       "riskScore": 8,
       "rpn": "",
       "sequence": 35,
       "severity": 4,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089345&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089346",
       "description": "Implementation errors",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Drilling Mechanics/Dynamics data through mud pulse telemetry, Data compression",
       "residualOccurence": 0,
       "residualRiskScore": 2,
       "residualSeverity": 2,
       "riskRegistryId": "36",
       "riskScore": 9,
       "rpn": "",
       "sequence": 36,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089346&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089347",
       "description": "Not enough flexibility in the frame structure for drilling dynamics data",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Drilling Mechanics/Dynamics data through mud pulse telemetry, Frame structure/downlink protocol",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "37",
       "riskScore": 6,
       "rpn": "",
       "sequence": 37,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089347&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089348",
       "description": "Target depth not achieved with the required reliability",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Demodulation error rates, Receivers and noise cancellation",
       "residualOccurence": 0,
       "residualRiskScore": 4,
       "residualSeverity": 2,
       "riskRegistryId": "38",
       "riskScore": 9,
       "rpn": "",
       "sequence": 38,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089348&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089350",
       "description": "Loss of experienced technical contributors",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Project Development Time, Overall Product",
       "residualOccurence": 0,
       "residualRiskScore": 6,
       "residualSeverity": 2,
       "riskRegistryId": "39",
       "riskScore": 6,
       "rpn": "",
       "sequence": 39,
       "severity": 2,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089350&ignoreViewGroup=true"
   },
   {
       "dbId": "1000089352",
       "description": "RSI from operating keyboard during development of software or using it",
       "detection": 0,
       "occurence": 0,
       "placesUsed": "Health, Safety and Environment, Overall Product",
       "residualOccurence": 0,
       "residualRiskScore": 0,
       "residualSeverity": 0,
       "riskRegistryId": "40",
       "riskScore": 6,
       "rpn": "",
       "sequence": 40,
       "severity": 3,
       "source": "Risk Register",
       "type": "",
       "urlToRiskRegistry": "/stature/control/loadSlbStudy?versionId=1000011035&viewName=RiskRegister&defaultRowId=1000089352&ignoreViewGroup=true"
   }
]
}
function getFields() {
    return [
        { name: 'dbId', type: 'long' },
        { name: 'description', type: 'string' },
        { name: 'detection', type: 'int' },
        { name: 'occurence', type: 'int' },
        { name: 'placesUsed', type: 'string' },
        { name: 'residualOccurence', type: 'int' },
        { name: 'residualRiskScore', type: 'int' },
        { name: 'residualSeverity', type: 'int' },
        { name: 'riskRegistryId', type: 'long' },
        { name: 'riskScore', type: 'int' },
        { name: 'rpn', type: 'string' },
        { name: 'sequence', type: 'int' },
        { name: 'severity', type: 'int' },
        { name: 'source', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'urlToRiskRegistry', type: 'string' }
    ]
}

function getParameters() {
    var o = {};
    o.theType = 'stature';
    o.theFields = getFields();

    o.theParams = { projectId: 97368 };
    o.theMethod = 'getRisks';
    o.theRecord = 'items';

    return o;
}

StartTest(function (t) {
    var o = getParameters()
    var store = getTheStore(o);
    store.load({
        params: o.theParams,
        callback: function () {
            t.isDeeply(getJsonOfStore(store), getResults(), t.url)
        }
    });
})

function getSoap() {
}

