function getResults() {
    return [
   {
       "id": "1",
       "achievedValue": "",
       "dbId": "1000088192",
       "description": "Pumps-off pressure profile compression specifications: http://omniworks.slb.com/SGL/OmniWorks/hspm/test/DataCompression/PumpOffPressureProfileCompression.zip",
       "maxRiskScore": 4,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000088365",
       "sequence": 1,
       "specification": "Spec 1",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "2",
       "achievedValue": "",
       "dbId": "1000088194",
       "description": "Pumps-off pressure profile compression specifications: http://omniworks.slb.com/SGL/OmniWorks/hspm/test/DataCompression/PumpOffPressureProfileCompression.zip",
       "maxRiskScore": 4,
       "reference": "",
       "req": "",
       "paeDbId": "1000088314",
       "reqDbId": "1000088365",
       "sequence": 1,
       "specification": "Spec 2",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "3",
       "achievedValue": "",
       "dbId": "1000088196",
       "description": "New frame structure - MODF",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088325",
       "reqDbId": "1000088365",
       "sequence": 1,
       "specification": "Spec 3",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "4",
       "achievedValue": "",
       "dbId": "1000088198",
       "description": "Receiver error rate at 1 bit error per 1000 bits or better",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088309",
       "reqDbId": "1000088365",
       "sequence": 1,
       "specification": "Spec 4",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "5",
       "achievedValue": "",
       "dbId": "1000088200",
       "description": "Pumps-off pressure profile compression specifications: http://omniworks.slb.com/SGL/OmniWorks/hspm/test/DataCompression/PumpOffPressureProfileCompression.zip",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088301",
       "reqDbId": "1000088365",
       "sequence": 1,
       "specification": "Spec 5",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "6",
       "achievedValue": "",
       "dbId": "1000088202",
       "description": "Apply single-curve compression algorithm to NGD measurements and provide compression code in C.  Sinlge-curve compression specifications are archived in http://omniworks.slb.com/SGL/OmniWorks/hspm/demod/compressiondll/data_compression_phase_3.doc",
       "maxRiskScore": 4,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000088415",
       "sequence": 6,
       "specification": "Spec 6",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "7",
       "achievedValue": "",
       "dbId": "1000088203",
       "description": "Receiver error rates should be kept to 1 bit error in 1000 bits",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088309",
       "reqDbId": "1000088415",
       "sequence": 1,
       "specification": "Spec 7",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "8",
       "achievedValue": "",
       "dbId": "1000088205",
       "description": "Apply single-curve decompression algorithm to retrieve NGD measurementa at surface. Sinlge-curve compression specifications are archived in http://omniworks.slb.com/SGL/OmniWorks/hspm/demod/compressiondll/data_compression_phase_3.doc",
       "maxRiskScore": 6,
       "reference": "",
       "req": "",
       "paeDbId": "1000088314",
       "reqDbId": "1000088415",
       "sequence": 8,
       "specification": "Spec 8",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "9",
       "achievedValue": "",
       "dbId": "1000088206",
       "description": "Design bandwidth efficient modulation capable of sending multiple bits per symbol (e.g. QAM) and also mechanically friendly to meet current siren modulator constraints",
       "maxRiskScore": 15,
       "reference": "",
       "req": "",
       "paeDbId": "1000088299",
       "reqDbId": "1000088458",
       "sequence": 9,
       "specification": "Spec 9",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "10",
       "achievedValue": "",
       "dbId": "1000088207",
       "description": "Spectrum analysis to detect best telemetry mode to use in current conditions in order to maximize SNR and bitrate.  Mode can be changed via downlink command or aadvise could be use in future run",
       "maxRiskScore": 9,
       "reference": "",
       "req": "",
       "paeDbId": "1000088323",
       "reqDbId": "1000088458",
       "sequence": 10,
       "specification": "Spec 10",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "11",
       "achievedValue": "",
       "dbId": "1000088208",
       "description": "Improve overall SNR by improving receiver performance, improving noise cancellation algorithms, better placement of sensors, proper selection of telemetry modes",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088304",
       "reqDbId": "1000088458",
       "sequence": 11,
       "specification": "Spec 11",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "12",
       "achievedValue": "",
       "dbId": "1000088209",
       "description": "Iterative Receiver capable of working reliably (1 bit error every 1000 bits or better) at lower SNR (down to 6 dB, currently 7.5 dB is the limit)",
       "maxRiskScore": 9,
       "reference": "",
       "req": "",
       "paeDbId": "1000088309",
       "reqDbId": "1000088458",
       "sequence": 12,
       "specification": "Spec 12",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "13",
       "achievedValue": "",
       "dbId": "1000088210",
       "description": "Model of surface rig system and well to estimate best placement of SPT sensors at surface in order to maximize SNR",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088307",
       "reqDbId": "1000088458",
       "sequence": 13,
       "specification": "Spec 13",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "14",
       "achievedValue": "",
       "dbId": "1000088211",
       "description": "Frame structure improvements - use MODF to send data that changes only after a particular event, thus freeing Repeating frames",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088325",
       "reqDbId": "1000088458",
       "sequence": 14,
       "specification": "Spec 14",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "15",
       "achievedValue": "",
       "dbId": "1000088212",
       "description": "Frame structure improvements - use MODF to send data that changes only after a particular event, thus freeing Repeating frames",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088301",
       "reqDbId": "1000088458",
       "sequence": 15,
       "specification": "Spec 15",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "52",
       "achievedValue": "",
       "dbId": "1000088256",
       "description": "Increase implementation of existing algorithms on most used tools",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088304",
       "reqDbId": "1000088516",
       "sequence": 52,
       "specification": "Spec 57",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "53",
       "achievedValue": "",
       "dbId": "1000088257",
       "description": "Increase implementation of existing algorithms on most used tools",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088289",
       "reqDbId": "1000088516",
       "sequence": 53,
       "specification": "Spec 58",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "16",
       "achievedValue": "",
       "dbId": "1000088213",
       "description": "Surface rig and well model algorithm",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088307",
       "reqDbId": "1000088546",
       "sequence": 1,
       "specification": "Spec 16",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "17",
       "achievedValue": "",
       "dbId": "1000088215",
       "description": "Apply compression algorithms that have been developed in the last few years (Sonic compression, Seismic compression, phase D/E pressure test compression, single-scan image compression, multi-curve compression)",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000088577",
       "sequence": 17,
       "specification": "Spec 19",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "18",
       "achievedValue": "",
       "dbId": "1000088216",
       "description": "Apply compression algorithms that have been developed in the last few years (Sonic compression, Seismic compression, phase D/E pressure test compression, single-scan image compression, multi-curve compression)",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088314",
       "reqDbId": "1000088577",
       "sequence": 18,
       "specification": "Spec 20",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "58",
       "achievedValue": "",
       "dbId": "1000088262",
       "description": "Developed training material",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088274",
       "reqDbId": "1000088611",
       "sequence": 58,
       "specification": "Spec 63",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "24",
       "achievedValue": "",
       "dbId": "1000088223",
       "description": "DDR/EMLA data compression specs in reference document",
       "maxRiskScore": 9,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000088638",
       "sequence": 1,
       "specification": "Spec 26",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "25",
       "achievedValue": "",
       "dbId": "1000088225",
       "description": "Receiver error rate at 1 bit error per 1000 bits or better",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088309",
       "reqDbId": "1000088638",
       "sequence": 1,
       "specification": "Spec 27",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "26",
       "achievedValue": "",
       "dbId": "1000088227",
       "description": "DDR/EMLA data compression specs in reference document",
       "maxRiskScore": 4,
       "reference": "",
       "req": "",
       "paeDbId": "1000088314",
       "reqDbId": "1000088638",
       "sequence": 1,
       "specification": "Spec 28",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "43",
       "achievedValue": "",
       "dbId": "1000088247",
       "description": "Less than one compression related failure over 100 runs",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088274",
       "reqDbId": "1000088679",
       "sequence": 43,
       "specification": "Spec 48",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "44",
       "achievedValue": "",
       "dbId": "1000088248",
       "description": "Receiver bit error ratea at 1 error per 1000 bits or better under normal drilling conditions",
       "maxRiskScore": 9,
       "reference": "",
       "req": "",
       "paeDbId": "1000088309",
       "reqDbId": "1000088706",
       "sequence": 44,
       "specification": "Spec 49",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "27",
       "achievedValue": "",
       "dbId": "1000088229",
       "description": "Apply cD&I and TF compression algorithms: http://omniworks.slb.com/SGL/OmniWorks/hspm/demod/decompression/CompDS6.doc",
       "maxRiskScore": 9,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000088738",
       "sequence": 27,
       "specification": "Spec 29",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "28",
       "achievedValue": "",
       "dbId": "1000088230",
       "description": "Apply decompression for cD&I and TF measurements: http://omniworks.slb.com/SGL/OmniWorks/hspm/demod/decompression/CompDS6.doc",
       "maxRiskScore": 4,
       "reference": "",
       "req": "",
       "paeDbId": "1000088314",
       "reqDbId": "1000088738",
       "sequence": 28,
       "specification": "Spec 30",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "29",
       "achievedValue": "",
       "dbId": "1000088231",
       "description": "Frame structure improvements - use MODF to send data that changes only after a particular event, thus freeing Repeating frames",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088325",
       "reqDbId": "1000088738",
       "sequence": 29,
       "specification": "Spec 31",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "30",
       "achievedValue": "",
       "dbId": "1000088232",
       "description": "Frame structure improvements - use MODF to send data that changes only after a particular event, thus freeing Repeating frames",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088301",
       "reqDbId": "1000088738",
       "sequence": 30,
       "specification": "Spec 32",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "42",
       "achievedValue": "",
       "dbId": "1000088246",
       "description": "Diagnostics and smart alarms to aide telemetry performance",
       "maxRiskScore": 9,
       "reference": "",
       "req": "",
       "paeDbId": "1000088323",
       "reqDbId": "1000088783",
       "sequence": 42,
       "specification": "Spec 47",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "45",
       "achievedValue": "",
       "dbId": "1000088249",
       "description": "Surface rig and well model",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088307",
       "reqDbId": "1000088814",
       "sequence": 45,
       "specification": "Spec 50",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "19",
       "achievedValue": "",
       "dbId": "1000088217",
       "description": "Compression of Phase D/E. Specs: hspm/test/DataCompression/DocumentsOnStethoScopePhaseECompression.zip",
       "maxRiskScore": 9,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000088845",
       "sequence": 19,
       "specification": "Spec 21",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "20",
       "achievedValue": "",
       "dbId": "1000088218",
       "description": "New frame structure - MODF",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088325",
       "reqDbId": "1000088845",
       "sequence": 1,
       "specification": "Spec 22",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "22",
       "achievedValue": "",
       "dbId": "1000088221",
       "description": "Shorter downlink commands",
       "maxRiskScore": 6,
       "reference": "",
       "req": "",
       "paeDbId": "1000088325",
       "reqDbId": "1000088845",
       "sequence": 22,
       "specification": "Spec 24",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "21",
       "achievedValue": "",
       "dbId": "1000088220",
       "description": "Compression of Phase D/E. Specs: hspm/test/DataCompression/DocumentsOnStethoScopePhaseECompression.zip",
       "maxRiskScore": 4,
       "reference": "",
       "req": "",
       "paeDbId": "1000088314",
       "reqDbId": "1000088845",
       "sequence": 21,
       "specification": "Spec 23",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "23",
       "achievedValue": "",
       "dbId": "1000088222",
       "description": "Frame structure improvements - use MODF to send data that changes only after a particular event, thus freeing Repeating frames",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088301",
       "reqDbId": "1000088845",
       "sequence": 23,
       "specification": "Spec 25",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "31",
       "achievedValue": "",
       "dbId": "1000088233",
       "description": "DMM compression",
       "maxRiskScore": 4,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000088892",
       "sequence": 31,
       "specification": "Spec 33",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "32",
       "achievedValue": "",
       "dbId": "1000088234",
       "description": "DMM compression",
       "maxRiskScore": 4,
       "reference": "",
       "req": "",
       "paeDbId": "1000088314",
       "reqDbId": "1000088892",
       "sequence": 32,
       "specification": "Spec 34",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "33",
       "achievedValue": "",
       "dbId": "1000088235",
       "description": "New frame structure - MODF",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088325",
       "reqDbId": "1000088892",
       "sequence": 1,
       "specification": "Spec 35",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "34",
       "achievedValue": "",
       "dbId": "1000088237",
       "description": "Frame structure improvements - use MODF to send data that changes only after a particular event, thus freeing Repeating frames",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088301",
       "reqDbId": "1000088892",
       "sequence": 34,
       "specification": "Spec 36",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "35",
       "achievedValue": "",
       "dbId": "1000088238",
       "description": "Apply cD&I and TF compression algorithms: http://omniworks.slb.com/SGL/OmniWorks/hspm/demod/decompression/CompDS6.doc",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000088935",
       "sequence": 35,
       "specification": "Spec 37",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "36",
       "achievedValue": "",
       "dbId": "1000088239",
       "description": "Apply decompression for cD&I and TF measurements: http://omniworks.slb.com/SGL/OmniWorks/hspm/demod/decompression/CompDS6.doc",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088314",
       "reqDbId": "1000088935",
       "sequence": 36,
       "specification": "Spec 39",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "48",
       "achievedValue": "",
       "dbId": "1000088252",
       "description": "Compressed dpoints should be easy to configure, surface algorithms should self configure.  If manual intervention is required, UI and GUI should be intuitive",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088274",
       "reqDbId": "1000088969",
       "sequence": 48,
       "specification": "Spec 53",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "54",
       "achievedValue": "",
       "dbId": "1000088258",
       "description": "Receivers, pump noise cancellation, decompression, diagnstics and smart alarms",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088304",
       "reqDbId": "1000088996",
       "sequence": 54,
       "specification": "Spec 59",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "55",
       "achievedValue": "",
       "dbId": "1000088259",
       "description": "Compression algorithms",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000089026",
       "sequence": 55,
       "specification": "Spec 60",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "56",
       "achievedValue": "",
       "dbId": "1000088260",
       "description": "Algorithms are measurement specific, not tool specific",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000089051",
       "sequence": 56,
       "specification": "Spec 61",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "37",
       "achievedValue": "",
       "dbId": "1000088240",
       "description": "Real-Time Compression and Transmission of LWD Borehole Seismic Waveforms using Segmental DCT and On-Demand Frame",
       "maxRiskScore": 9,
       "reference": "",
       "req": "",
       "paeDbId": "1000088290",
       "reqDbId": "1000089076",
       "sequence": 37,
       "specification": "Spec 41",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "38",
       "achievedValue": "",
       "dbId": "1000088241",
       "description": "Real-Time Compression and Transmission of LWD Borehole Seismic Waveforms using Segmental DCT and On-Demand Frame",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088309",
       "reqDbId": "1000089076",
       "sequence": 38,
       "specification": "Spec 42",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "39",
       "achievedValue": "",
       "dbId": "1000088242",
       "description": "Real-Time Compression and Transmission of LWD Borehole Seismic Waveforms using Segmental DCT and On-Demand Frame",
       "maxRiskScore": 4,
       "reference": "",
       "req": "",
       "paeDbId": "1000088314",
       "reqDbId": "1000089076",
       "sequence": 39,
       "specification": "Spec 44",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "40",
       "achievedValue": "",
       "dbId": "1000088243",
       "description": "New frame structure - MODF",
       "maxRiskScore": 2,
       "reference": "",
       "req": "",
       "paeDbId": "1000088325",
       "reqDbId": "1000089076",
       "sequence": 1,
       "specification": "Spec 45",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "41",
       "achievedValue": "",
       "dbId": "1000088245",
       "description": "Frame structure improvements - use MODF to send data that changes only after a particular event, thus freeing Repeating frames",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088301",
       "reqDbId": "1000089076",
       "sequence": 41,
       "specification": "Spec 46",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "46",
       "achievedValue": "",
       "dbId": "1000088250",
       "description": "Algorithms for downhole tool distributed with downhole tool firmware, algorithms for surface distributed with HSPM",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088274",
       "reqDbId": "1000089124",
       "sequence": 46,
       "specification": "Spec 51",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "47",
       "achievedValue": "",
       "dbId": "1000088251",
       "description": "InTouch engineers will be trained on the use of new applications, SMEs available",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088274",
       "reqDbId": "1000089149",
       "sequence": 47,
       "specification": "Spec 52",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "49",
       "achievedValue": "",
       "dbId": "1000088253",
       "description": "Mostly software development",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088274",
       "reqDbId": "1000089174",
       "sequence": 49,
       "specification": "Spec 54",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "50",
       "achievedValue": "",
       "dbId": "1000088254",
       "description": "Development time according to approved schedule",
       "maxRiskScore": 3,
       "reference": "",
       "req": "",
       "paeDbId": "1000088274",
       "reqDbId": "1000089199",
       "sequence": 50,
       "specification": "Spec 55",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "51",
       "achievedValue": "",
       "dbId": "1000088255",
       "description": "Keep development budget",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088274",
       "reqDbId": "1000089226",
       "sequence": 51,
       "specification": "Spec 56",
       "target": "",
       "tolerance": ""
   },
   {
       "id": "57",
       "achievedValue": "",
       "dbId": "1000088261",
       "description": "Help files created for all surface applications in HSPM",
       "maxRiskScore": 0,
       "reference": "",
       "req": "",
       "paeDbId": "1000088304",
       "reqDbId": "1000089251",
       "sequence": 57,
       "specification": "Spec 62",
       "target": "",
       "tolerance": ""
   }
]
}
function getFields() {
    return [
        { name: 'achievedValue', type: 'string' },
        { name: 'dbId', type: 'long' },
        { name: 'description', type: 'string' },
        { name: 'id', type: 'long' },
        { name: 'maxRiskScore', type: 'int' },
        { name: 'reference', type: 'string' },
		{ name: 'req', type: 'string' },
        { name: 'paeDbId', type: 'long' },
        { name: 'reqDbId', type: 'long' },
        { name: 'sequence', type: 'int' },
        { name: 'specification', type: 'string' },
        { name: 'target', type: 'string' },
        { name: 'tolerance', type: 'string' }
    ]
}

function getParameters() {
    var o = {};
    o.theType = 'stature';
    o.theFields = getFields();

    o.theParams = { projectId: 97368 };
    o.theMethod = 'getSpecifications';
    o.theRecord = 'specifications';

    return o;
}

StartTest(function (t) {
    var o = getParameters()
    var store = getTheStore(o);
    store.load({
        params: o.theParams,
        callback: function () {
            t.isDeeply(getJsonOfStore(store), getResults(), t.url)
        }
    });
})

function getSoap() {
}

