function getResults() {
    return [
   {
       "id": "1",
       "dbId": "1000088134",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 1,
       "status": "Planned",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "2",
       "dbId": "1000088135",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 2,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "3",
       "dbId": "1000088136",
       "details": "Test Plan",
       "dueByCDP": "Project Closure",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 3,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "4",
       "dbId": "1000088137",
       "details": "Field tests",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 4,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "5",
       "dbId": "1000088138",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 5,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "6",
       "dbId": "1000088139",
       "details": "Review training material",
       "dueByCDP": "Project Closure",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 6,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "7",
       "dbId": "1000088140",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 7,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "8",
       "dbId": "1000088141",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 8,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "9",
       "dbId": "1000088142",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 9,
       "status": "Planned",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "10",
       "dbId": "1000088143",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 10,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "11",
       "dbId": "1000088144",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 11,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "12",
       "dbId": "1000088145",
       "details": "",
       "dueByCDP": "Project Closure",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 12,
       "status": "Planned",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "13",
       "dbId": "1000088146",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 13,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "14",
       "dbId": "1000088147",
       "details": "External review of help files",
       "dueByCDP": "Project Closure",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 14,
       "status": "Planned",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "15",
       "dbId": "1000088148",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Data compression",
       "passFail": "Pass",
       "responsiblePersonUsername": "",
       "sequence": 15,
       "status": "Completed",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "16",
       "dbId": "1000088149",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Decompression",
       "passFail": "Pass",
       "responsiblePersonUsername": "",
       "sequence": 16,
       "status": "Completed",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "17",
       "dbId": "1000088150",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Frame structure/downlink protocol",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 17,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "18",
       "dbId": "1000088151",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Receivers and noise cancellation",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 18,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "19",
       "dbId": "1000088152",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "MWD BHA master logic",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 19,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "20",
       "dbId": "1000088153",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Data compression",
       "passFail": "Pass",
       "responsiblePersonUsername": "",
       "sequence": 20,
       "status": "Completed",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "21",
       "dbId": "1000088154",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Decompression",
       "passFail": "Pass",
       "responsiblePersonUsername": "",
       "sequence": 21,
       "status": "Completed",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "22",
       "dbId": "1000088155",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Modulation",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 22,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "23",
       "dbId": "1000088156",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Diagnostics, alarms, and automation",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 23,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "24",
       "dbId": "1000088157",
       "details": "",
       "dueByCDP": "Project Closure",
       "group": "",
       "pae": "Surface",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 24,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "25",
       "dbId": "1000088158",
       "details": "",
       "dueByCDP": "Realization Launch",
       "group": "",
       "pae": "Receivers and noise cancellation",
       "passFail": "Fail",
       "responsiblePersonUsername": "",
       "sequence": 25,
       "status": "Completed",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "26",
       "dbId": "1000088159",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Pre-job preparation",
       "passFail": "Pass",
       "responsiblePersonUsername": "",
       "sequence": 26,
       "status": "Completed",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "27",
       "dbId": "1000088160",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Data compression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 27,
       "status": "Planned",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "28",
       "dbId": "1000088161",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Decompression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 28,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "29",
       "dbId": "1000088162",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Data compression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 29,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "30",
       "dbId": "1000088163",
       "details": "Basket tests",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Frame structure/downlink protocol",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 30,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "31",
       "dbId": "1000088164",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Decompression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 31,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "32",
       "dbId": "1000088165",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Frame structure/downlink protocol",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 32,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "33",
       "dbId": "1000088166",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "MWD BHA master logic",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 33,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "34",
       "dbId": "1000088167",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Data compression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 34,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "35",
       "dbId": "1000088168",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "Receivers and noise cancellation",
       "passFail": "Pass",
       "responsiblePersonUsername": "",
       "sequence": 35,
       "status": "Completed",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "36",
       "dbId": "1000088169",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Decompression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 36,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "37",
       "dbId": "1000088170",
       "details": "",
       "dueByCDP": "Field Introduction",
       "group": "",
       "pae": "Data compression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 37,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "38",
       "dbId": "1000088171",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Decompression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 38,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "39",
       "dbId": "1000088172",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Data compression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 39,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "40",
       "dbId": "1000088173",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Decompression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 40,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "41",
       "dbId": "1000088174",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Data compression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 41,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "42",
       "dbId": "1000088175",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Decompression",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 42,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "43",
       "dbId": "1000088176",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Receivers and noise cancellation",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 43,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "44",
       "dbId": "1000088177",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Surface",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 44,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "45",
       "dbId": "1000088178",
       "details": "Basket tests",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 45,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "46",
       "dbId": "1000088179",
       "details": "Lab tests on CPU usage on field computers",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 46,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "47",
       "dbId": "1000088180",
       "details": "Test Plan",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 47,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "48",
       "dbId": "1000088181",
       "details": "Test model with existing rig data",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 48,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "49",
       "dbId": "1000088182",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "Pass",
       "responsiblePersonUsername": "",
       "sequence": 49,
       "status": "Completed",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "50",
       "dbId": "1000088183",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 50,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "51",
       "dbId": "1000088184",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "Overall Product",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 51,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "52",
       "dbId": "1000088185",
       "details": "",
       "dueByCDP": "Business Commercialization",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 52,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "53",
       "dbId": "1000088186",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 53,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "54",
       "dbId": "1000088187",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 54,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "55",
       "dbId": "1000107610",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 55,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "56",
       "dbId": "1000107609",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 56,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   },
   {
       "id": "57",
       "dbId": "1000107608",
       "details": "",
       "dueByCDP": "",
       "group": "",
       "pae": "",
       "passFail": "",
       "responsiblePersonUsername": "",
       "sequence": 57,
       "status": "",
       "targetCompletionDate": "",
       "testActivities": ""
   }
]
}
function getFields() {
    return [
        { name: 'id', type: 'long' },
        { name: 'dbId', type: 'long' },
        { name: 'details', type: 'string' },
        { name: 'dueByCDP', type: 'string' },
        { name: 'group', type: 'string' },
        { name: 'pae', type: 'string' },
        { name: 'passFail', type: 'string' },
        { name: 'responsiblePersonUsername', type: 'string' },
        { name: 'sequence', type: 'int' },
        { name: 'status', type: 'string' },
        { name: 'targetCompletionDate', type: 'dateTime' },
        { name: 'testActivities', type: 'string' }
    ]
}

function getParameters() {
    var o = {};
    o.theType = 'stature';
    o.theFields = getFields();

    o.theParams = { projectId: 97368 };
    o.theMethod = 'getTests';
    o.theRecord = 'tests';

    return o;
}

StartTest(function (t) {
    var o = getParameters()
    var store = getTheStore(o);
    store.load({
        params: o.theParams,
        callback: function () {
            t.isDeeply(getJsonOfStore(store), getResults(), t.url)
        }
    });
})

function getSoap() {
}

